create table if not exists users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    encoded_password varchar(255) not null,
    phone_number varchar(255) not null,
    role varchar(255) not null check ((role in ('ROLE_ADMIN','ROLE_USER'))),
    user_name varchar(255) not null,
    active boolean not null,
    created_at timestamp(6) not null,
    deleted_at timestamp(6)
    );
create table if not exists accounts (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    account_number varchar(20) not null unique,
    user_name varchar(255) not null,
    deposit numeric(19,2) not null,
    principal numeric(19,2) not null,
    updated_at timestamp(6) with time zone not null,
    created_at timestamp(6) with time zone not null
    );
create table if not exists holdings (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    stock_code varchar(20) not null,
    avg_price numeric(19,2) not null,
    blocked_quantity bigint,
    total_quantity bigint not null
    );
create table if not exists orders (
    id bigint generated by default as identity primary key,
    account_id bigint not null,
    stock_code varchar(20) not null,
    order_side varchar(10) not null check ((order_side in ('BUY','SELL'))),
    order_type varchar(20) not null check ((order_type in ('MARKET','LIMIT'))),
    order_status varchar(20) not null check ((order_status in ('PENDING','SUBMITTED','FILLED','CANCELLED','REJECTED','EXPIRED'))),
    quantity bigint not null,
    limit_price numeric(19,2),
    blocked_deposit numeric(19,2),
    executed_price numeric(19,2),
    recovery_count integer not null,
    created_at timestamp(6) with time zone not null,
    executed_quantity bigint,
    updated_at timestamp(6) with time zone not null,
    version bigint,
    reject_reason varchar(255) check ((reject_reason in ('INSUFFICIENT_FUNDS')))
    );
create table if not exists watchlists (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    stock_code varchar(255) not null,
    stock_name varchar(255),
    constraint uk_watchlist_user_stock unique (user_id, stock_code)
    );
create index idx_orders_account_created on orders (account_id, created_at desc);
create index idx_orders_status_type_created on orders (order_status, order_type, created_at);
create index idx_orders_stock_code on orders (stock_code);
create index idx_orders_created_at on orders (created_at);
alter table if exists holdings add constraint fk_holdings_accounts_id foreign key (account_id) references accounts;